{% set name = "pandas-plink" %}
{% set version = "1.2.18" %}
{% set sha256 = "6f476b591e6863a2995c8b446c10753fdf03b0b666cd567283b5fc2dbd789df2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
    - cffi >=1.7
  run:
    - python
    - cffi >=1.7
    - numpy >=1.11
    - pandas >=0.17
    - toolz >=0.8
    - dask >=0.14
    - tqdm >=4.15

test:
  requires:
    - pytest
    - pytest-pep8
  imports:
    - pandas
    - pandas_plink
  commands:
    - python -c "import sys; import pandas; import pandas_plink; sys.exit(pandas_plink.test())"

about:
  home: https://github.com/limix/pandas-plink
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Convert PLINK files to Pandas data frame'
  doc_url: https://pandas-plink.readthedocs.io
  dev_url: https://github.com/limix/pandas-plink

extra:
  recipe-maintainers:
    - Horta
