{% set name = "pandas-plink" %}
{% set version = "1.2.2" %}
{% set sha256 = "e735a53473e8ec1097b017b40095f5c9b4a40bebf95854d27523404f2455dd65" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win32 or linux32]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
    - cffi >=1.7
  run:
    - python
    - cffi >=1.7
    - numpy >=1.11
    - pandas >=0.17
    - toolz >=0.8
    - dask >=0.14

test:
  requires:
    - pytest >=3
  imports:
    - pandas_plink
  commands:
    - python -c "import sys; import pandas_plink; sys.exit(pandas_plink.test())"

about:
  home: https://github.com/limix/pandas-plink
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Convert PLINK files to Pandas data frame'
  doc_url: https://pandas-plink.readthedocs.io
  dev_url: https://github.com/limix/pandas-plink

extra:
  recipe-maintainers:
    - Horta
