{% set name = "pandas-plink" %}
{% set version = "1.2.30" %}
{% set sha256 = "fea882029f93a7db03680b7e02205822380b7c0b5d7435c1ac7a6b6513151e09" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pandas_plink-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    - "{{ compiler('c') }}"
  host:
    - python
    - pip
    - pytest-runner
    - cffi >=1.7
  run:
    - cffi >=1.7
    - dask >=1.0
    - numpy >=1.12
    - pandas >=0.23
    - pytest >=3.3.2
    - pytest-runner >=4.2
    - python
    - toolz >=0.9
    - tqdm >=4.15

test:
  requires:
    - pytest
    - pytest-pep8
  imports:
    - pandas
    - pandas_plink
  commands:
    - python -c "import sys; import pandas; import pandas_plink; sys.exit(pandas_plink.test())"

about:
  home: https://github.com/limix/pandas-plink
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Convert PLINK files to Pandas data frame'
  doc_url: https://pandas-plink.readthedocs.io
  dev_url: https://github.com/limix/pandas-plink

extra:
  recipe-maintainers:
    - Horta
