{% set name = "pandas-plink" %}
{% set version = "2.2.5" %}
{% set sha256 = "f109c1d156b37e04cb1400c83ec4a2beedb90ff7e5bae10035e5bcf1d754448c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pandas_plink-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - pytest-runner
    - cffi >=1.14.3
  run:
    - Deprecated >=1.2.6
    - cffi >=1.14.3
    - dask >=2.6.0
    - numpy >=1.17.2
    - pandas >=1.1.3
    - pytest >=5.2.2
    - python
    - toolz >=0.9
    - tqdm >=4.36.1
    - xarray >=0.16.1
    - zstandard >=0.13.0

test:
  imports:
    - pandas
    - pandas_plink
  commands:
    - python -c "import sys; import pandas; import pandas_plink; sys.exit(pandas_plink.test())"

about:
  home: https://github.com/limix/pandas-plink
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Convert PLINK files to data array
  doc_url: https://pandas-plink.readthedocs.io
  dev_url: https://github.com/limix/pandas-plink

extra:
  recipe-maintainers:
    - Horta
