{% set name = "pandas-plink" %}
{% set version = "2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pandas_plink-{{ version }}.tar.gz
  sha256: f5e5a0ee588c65edea7ea44953523221eb3cf8367700fa5407ad6d72de0a85d9

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - python >=3.10                       # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - python >=3.10
    - pip
    - poetry-core
    - cffi >=1.14.3
  run:
    - Deprecated >=1.2.6
    - cffi >=1.14.3
    - dask >=2.6.0
    - numpy >=1.17.2
    - pandas >=1.1.3
    - pandera-base
    - pytest >=5.2.2
    - python >=3.10
    - tqdm >=4.36.1
    - xarray >=0.18.2
    - zstandard >=0.13.0

test:
  imports:
    - pandas
    - pandas_plink

about:
  home: https://github.com/limix/pandas-plink
  license: MIT
  license_file: LICENSE.md
  summary: Convert PLINK files to data array
  doc_url: https://pandas-plink.readthedocs.io
  dev_url: https://github.com/limix/pandas-plink

extra:
  recipe-maintainers:
    - danielnachun
    - Horta
