appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: GPj3G7xWH6+UTChV/HAg822yWGQRuzSkQc8WhguNVopp5lHos6exS+8xE76zuvRu/3+WxiqF5dzTrtoN1jEPxfAjYQZz+KJIYL2zgSxdZeq64VCxv7k01Lh5XgHKiPspxPSw0dMwte/axTiR9/cLyFzHqgs0509+fe6FOGGcdsimX/WBezdMwrHj2rZQZaiTTBWpz25ws1xSGivPoJNLMlpSVHh1Xih74oRAvBN5aNdzZEHO1N/UxuZbX/xf5CaM4EqRWrKDC2lKxD1wDbrq09GtQ0kqYhHZ5nkgSVGgQqUpL164h2r4aLdCWW/WHiaBrHgU/qtz4FSc6Fr4xEF15bfSjgLydDaU5EerSzQmhubbxpg5BR4jE0SwTBeaTEEbaCS6/XBmd0eekHDKjW/EXE6v/mkwtzIpTejnOJQyOtdIOq9VwLObm4FOcMGmWfL+iG5DVFThePb8OFxe9YN2PSvfZejVjUqnlhQfjRXdpo7hJMKtMIU7vH7qbOUMbd+HTpgfgie4eH3I65Xy9a1r9lzLve1EdNfzQuOKgDRcn0yInG29mRsaOBchioudYTIBD5STiStVzza55Pyhoe5zlplhqUjP+IO4eNiSJnCOGSxB05urKV3roJhKF6sK9v6njgzZfuJB2dfhuKdB2cUvQs5iu6ZamiozibSlXRy/ecg=}
