travis:
  secure:
    BINSTAR_TOKEN: ln/6ua9okmCIeGUzqmuV6+4F9PNm5tKYhR0RjU/r8qQnwSFG9HnokWQEeZO/Sl8ZBEdmpJHd+AOqIm8/jWJatNB3R7SiVyBtn6OLIrPkWqvjJ4tiorOJEHifOyRz+n0AiBgqcGfjX6yHhJEw5ju75wgFh4s4Zlqe1NfTdW8far0USmp/0JQHNGrF1dRaX5a0IZ/OAPZO5pcHCutlUuryKAWhHNKAVCXLo6Urb2CV6odGkkdBhLRWjDftAgYIDdwwwAJVoG9N5TOHKiRMt9w5atXfwggdidLa21qJOYrQAWrrsxrWIbMn/qNVou8cA7tJFKHeWHufpQE/hOWFWCovo88wmhHPqPAABxQZFPRFOdOboIRsx2EHXNKUBLE1pljp+sn0NPHWsClSwCXXZ2W4sxMFq4JoOWZTLIKRnWyRGUESxv/gma+C1PJ5t6oLFDMKq9vZqqSecLeuy/uTmsJ7gU/pRWCDt4+LRBxCB7V/0OfV36jkNraFnshl0uKO0tXVzTlOaRydCKb+dxzwuYkrgDoVQIjeyS9bl+1+JjJAVJsZDHNSIZj54yxkSRBw0UK+sRnyNz4CgZMO4hu7hqGpXRX24w18UD9xDbX/FWvNoZbPIqjtOPwolV+l21DzoG8W1/oNh8Rk8PYvmJadJZzZtcV0sC96lmGzWBPsGE1t8zI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
