travis:
  secure:
    BINSTAR_TOKEN: MBEqpHcqauy4Dnd23TuXNhVpSRqwn7KhfNStTQHz9c7XSZ5keaJmigLTMTvPOpsqQTJp2V6yQMp6Xt5+pHlbwmd+3ZyZP7+PRCHL1IV0b34knrIv8UHETZJBNc2ACxb5QdFMV4BM9yLZLiLndA+2yVLnLf8/lXD3UwbM/P+XCCC6DtB/rQ0ZQdoDzw48AiIBi8t9a198I557AdrrVmdRXpgEvSCmOrVSoC3/ZQyT+LhR3VJDLSkBrNwwL4aY1jLfB/f/sZe7b0ylelu0IzYTOLtAy73sZdQUqYAS1GcPmVM1LNZ9kd2xcoYe4ayk5E6+bwWeKPbSwlxphYfgYfLSHvk9GT3PpPahzjM9zYmxJsLBQs7ay6R9CZ5IJGLxzaQHf1JYqqxxKw+/6Aaz3GEHtGpowaMOGHPm1ZT+p6lMGIk+0w3qCTPNowUMFIE/qx4AGlAnbqtDqyshObt2WTlndcKwUFJ3tky582iQLvjRXVsz+S/aCZqo4ZIPBgt02wvP5kR3Yg60X7egr8tjf0Ilfh1/g1bdqyW1OrGB1MfCeqGs5oOqDd+8Fmm4EHxdSSccmBztrVEIjitw7tJ9neDPvM2gFcXkRsesqhTWyrn1iBjWBRJHQNtLiUvGOfrnKuKA7oj2S2xoucDb8rc+J7JHvbustAGNp6Y0GIYrIOHsL/4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
