travis:
  secure:
    BINSTAR_TOKEN: o6UbTJWPnW2/n0jO3Z92qQBBbtJFutfx2qGADPPVKZQMfDqkvBEwzYmgAhULFZxAplYT2HhSWA0JRl8qI16flGIMUKPvAPXvZzJ8j81syAQQ5pdVYn5wh6tN08edQV7huFfbV0aJHFZhjQwJ6UgmLKr16oJI+PfDcPAVf5QVWMC4LMhB7tsLpnz+i4nanhHwJFQcvOLWsfNO7Wxy//BS6p+1T4aTI6Jzkdhj++kXGt/DA495cA6diQ3dvJaWuMPT95W+1n01IljkEqGZ1GAdG+eLvkD86dbCq5jYP1gUuEhXWSi9qPF+SZnlO1068qPVRmMDvnaXwfSFZuq2ivdZAcHRBM8LG1Msx138tHI837bqPdlQjB8Pc7J0AnAyui9g86Fc6NZKlS5SDaBVW+mPX+yRB7QvNJGPfXPKLfYeyzpOt1hqH0Wz3aofv5/d6hNezFBdt9hp2kwuqWYagtQNHWUwWBBLcffxbLIEvXjr4ccXE1iYJe9G+JXYW/EzTfuxPuZBbuNypGCbAy5S9Z1h71pR8TTKrIpqeoFBb1osch/U7lnYEVo56srxwKMYgyq+XpRNmzQIZEx/PgwTfDbpWVZ23OcDbAGAZbbY6e8CIpGG9OahAVhtckiKqANTWQ4wr1IQ84JUtPZtqKDHgJ6PnRJADE95/hffbmsK+d+N9JU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
